limit: 3
line: qn
streamers:
  PxPcrm05mPM.webm:
    copyright: 2
    cover: PxPcrm05mPM.jpg
    desc: "\u642C\u8FD0\uFF1Ahttps://www.youtube.com/watch?v=PxPcrm05mPM"
    desc_format_id: 0
    dolby: 0
    dynamic: ''
    open_subtitle: false
    source: https://www.youtube.com/watch?v=PxPcrm05mPM
    subtitle:
      lan: ''
      open: 0
    tag: "youtube,\u642C\u8FD0,\u7FFB\u65B0"
    tid: 232
    title: Finally Ready For Paint - Mercedes W123 Restoration
